title: Fabricate
email: matt@misterpotts.uk
description: >- 
  End user documentation for the Foundry Virtual Tabletop (VTT) Module, "Fabricate".
  Fabricate is a system-agnostic, flexible crafting module for Foundry VTT.
baseurl: "/fabricate"
url: https://misterpotts.github.io
github_username:  misterpotts

# Build settings
theme: just-the-docs

permalink: pretty

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red