title: Fabricate
email: matt@misterpotts.uk
description: >- 
  End user documentation for the Foundry Virtual Tabletop (VTT) Module, "Fabricate".
  Fabricate is a system-agnostic, flexible crafting module for Foundry VTT.
baseurl: ""
url: https://misterpotts.github.io/fabricate
github_username:  misterpotts

# Build settings
theme: just-the-docs

permalink: pretty